---

- get_url: url={{ arch_chroot_url }} dest={{ arch_chroot_archive }}
- stat: path={{ arch_chroot }}
  register: st
- unarchive: src={{ arch_chroot_archive }} dest={{ arch_chroot_prefix }} copy=no
  when: not st.stat.exists
- template: src=etc/pacman.d/mirrorlist dest={{ arch_chroot }}/etc/pacman.d/mirrorlist
- fetch: src=/etc/resolv.conf dest=/tmp/resolv.conf
  register: f
- copy: src="{{ f.dest }}" dest={{ arch_chroot }}/etc
- mount: src=/{{ item }} name={{ arch_chroot }}/{{ item }} fstype=bind state=mounted opts=rbind
  with_items:
    - proc
    - sys
    - dev
    - run
- stat: path={{ arch_chroot }}/etc/pacman.d/gnupg/trustdb.gpg
  register: st
- shell: chroot {{ arch_chroot }} pacman-key --init
  when: not st.stat.exists
- shell: chroot {{ arch_chroot }} pacman-key --populate archlinux
  when: not st.stat.exists
