---
- mount: src={{ btrfs_dev }} name={{ arch_root }} opts='subvol=arch' fstype=btrfs state=mounted

- file: path={{ arch_root }}/{{ item }} state=directory
  with_items:
    - root
    - home
    - var
    - srv
    - dev
    - sys
    - proc
    - run
    - etc

- mount: src=/dev/sda name={{ arch_root }}/{{ item }} opts='subvol={{ item }}' fstype=btrfs state=mounted
  with_items:
    - root
    - home
    - var
    - srv

- stat: path={{ arch_root }}/boot/grub
  register: st

- include: _root_sys_mount.yml
  when: st.stat.exists

- fetch: src=/etc/resolv.conf dest=/tmp/resolv.conf
  register: f

- copy: src="{{ f.dest }}" dest={{ arch_root }}/etc/resolv.conf
